
server:
  port: ${PORT:0}
  servlet:
    context-path: /api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}    
  
# To See H2 Console in Browser:
# http://localhost:{port}/api/h2-console
# Enabling H2 Console
spring:
  application:
    name: transaction-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:transactionDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    
 # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    #defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
        
##Connect kafka
  kafka:
    template:
      default-topic: transaction-topic
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap:
          servers: localhost:9092
        
        
