server:
  port: 8090


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#          lower-case-service-id: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/cuentas/**
            - Method=GET,POST,PUT,DELETE

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/clientes/**
            - Method=GET,POST,PUT,DELETE
            
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/movimientos/**
            - Method=GET,POST,PUT,DELETE